- name: import taps
  register: result
  homebrew_tap: tap={{ item }} state=present
  with_items: homebrew_taps
  sudo: false

- name: install homebrew_cask
  homebrew: name=brew-cask state=latest
  sudo: false

- name: install and update homebrew_cask packages
  homebrew_cask: 
    name={{ item.name | default(item) }} 
    state={{ item.state | default('installed') }}
  with_items: homebrew_cask_packages
  sudo: false